name: Go CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -v

  lint:
    name: Run Go Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

      - name: Run GolangCI-Lint
        run: golangci-lint run ./...

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Run Tests
        run: go test ./...

      - name: Build for Linux
        run: make app-linux

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-linux
          path: ./bin/app-linux-amd64

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: systemd-service
          path: ./deployment/systemd/check-tc.service

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: app-linux

      - name: Download deployment artifact
        uses: actions/download-artifact@v3
        with:
          name: systemd-service

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y ssh

      - name: Add SSH key and configure known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keygen -R ${{ secrets.SERVER_IP }} || true
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Create target directory on the server
        run: |
          ssh root@${{ secrets.SERVER_IP }} "mkdir -p /opt/check-tc/bin /opt/check-tc/deployment"

      - name: List all files in the working directory (before sync)
        run: |
          echo "Listing files in current directory: $PWD"
          ls -R .    

      - name: Stop the service before uploading new version
        run: |
          ssh root@${{ secrets.SERVER_IP }} "systemctl stop check-tc.service"

      - name: Upload binary file to the server
        run: |
          echo "Uploading app-linux binary to the server..."
          scp ./app-linux-amd64 root@${{ secrets.SERVER_IP }}:/opt/check-tc/bin/app-linux-amd64

      - name: Upload deployment directory to the server
        run: |
          echo "Uploading deployment directory to the server..."
          scp ./check-tc.service root@${{ secrets.SERVER_IP }}:/opt/check-tc/deployment/check-tc.service

      - name: Set permissions for binary
        run: |
          ssh root@${{ secrets.SERVER_IP }} "chmod +x /opt/check-tc/bin/app-linux-amd64"

      - name: Set permissions for deployment file
        run: |
          ssh root@${{ secrets.SERVER_IP }} "chmod 644 /opt/check-tc/deployment/check-tc.service"

      - name: Restart and enable the systemd service
        run: |
          ssh root@${{ secrets.SERVER_IP }} "systemctl daemon-reload && systemctl enable check-tc.service && systemctl restart check-tc.service && systemctl status check-tc.service"
